Add support incremental loading with order by clauses
trocco-io/embulk-input-soql_file pull request #15
Opened 2024-08-29 06:43 UTC by ziguzagu

差分転送をサポートするための実装です。

# 仕様

JDBC 系の差分転送機能と同様の使用感となるよう、設定の意味変更、追加をしています。

- 変更
    - **object**: 差分転送時にテーブル名として利用。
    - **soql**: SOQL。指定内容で全件取得する。差分転送時には無視される。
- 追加
    - **incremental**: 差分転送の可否（boolean、デフォルトは false）
    - **incremental_columns**: 差分転送の条件として利用するカラム（文字列の配列）
    - **last_record**: 差分転送の条件として指定する値（incremental_columns と同順。文字列の配列）
    - **select**: 差分転送時の SELECT 句（文字列）
    - **where**: 差分転送時の WHERE 句（文字列）

## 差分転送

`incremental` が true でかつ `incremental_columns` が空でない場合に差分転送の動作となります。

差分転送では `select`, `where`, `incremental_columns`, `last_record` の値から SOQL を生成しリクエストを行います。このとき、`incremental_columns` に指定された列で ORDER BY 句も付加します。

クエリの結果として出力される CSV を取得し、最終行から `incremental_columns` に指定されたカラムを取得して `last_record` の値として ConfigDiff を生成します。

# 実装概要

差分転送モードでの動作は以下のような流れになります。

- SoqlFilePlugin#open
    -  全ての CSV をダウンロードし一時ファイルとして保存
- CsvFileInput (SoqlFileInput の名前を変更）
    - ダウンロードした CSV群 を TransactionalFileInput として処理できるよう実装
    - SoqlFilePlugin#open の返却値になる
- CsvFileInput#commit
    -  最後の CSV から指定カラム最大値の取得し TaskReport として記録
- SoqlFilePlugin#transaction, resume
    - TaskReport から ConfigDiff を生成する

2025-01-20 07:06 UTC, d-hrs commented on src/main/java/org/embulk/input/soql/CsvFileInput.java
> +        List<CSVRecord> records = parser.getRecords();
csvファイルの1ファイルあたりのサイズはいくつですか？ファイルサイズが大きい場合 `getRecords()` するとOOMする可能性があるのでは、と思います。
もしサイズが大きい場合は `getRecords()` を利用せずに `lastRecord` を取得するよう修正してください。

2025-01-20 07:29 UTC, d-hrs commented on src/main/java/org/embulk/input/soql/SoqlBuilder.java
> +        // 差分転送のための WHERE 句を生成する:
embulk-output-jdbcと同様のロジック
https://github.com/embulk/embulk-input-jdbc/blob/d49aadb724597d9acc71d7201a48f9add70fcea5/embulk-input-jdbc/src/main/java/org/embulk/input/jdbc/JdbcInputConnection.java#L323-L359

2025-01-20 08:55 UTC, d-hrs commented on src/main/java/org/embulk/input/soql/SoqlBuilder.java
> +            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'");
timestampとして利用できるフォーマットは以下のようです。
https://developer.salesforce.com/docs/atlas.ja-jp.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_dateformats.htm

フォーマットが `yyyy-MM-dd'T'HH:mm:ss.SSS'Z'` 固定だと、例に記載の値はすべて `false` になりそうです
![image](https://github.com/user-attachments/assets/4cc8e326-bba4-4c7c-b6d6-fa30c907a7b4)

`return "'" + value.replace("'", "\\'") + "'";` されるだけで実質的な影響はなさそうですが、想定している処理ではないと思うので `java.time.ZonedDateTime.parse` で処理するとよさそうです
```java
  java.time.ZonedDateTime.parse(value, DateTimeFormatter.ISO_ZONED_DATE_TIME);
```

2025-01-20 08:56 UTC, d-hrs requested changes
確認お願いします！

2025-01-20 10:34 UTC, chikamura commented on src/main/java/org/embulk/input/soql/CsvFileInput.java
> +    protected List<String> getLastRecords(Path csvFilePath, List<String> columns)
一つ目の引数の csvFilePath は使われていないので、引数から削除してよさそうです。
（40行目と60行目の最後のレコードを取得する処理が被っている）

2025-01-20 10:34 UTC, chikamura commented on src/main/java/org/embulk/input/soql/SoqlFilePlugin.java
> +                throw new ConfigException("soql with incremental doesn't support");
nits:

他の input-plugin では[クエリとincrementalが併用可能なものもある（use_raw_query_with_incremental のサポート）](https://github.com/embulk/embulk-input-jdbc/blob/v0.13.2/embulk-input-mysql/README.md#use-incremental-loading-with-raw-query)ので、
README に soql と incremental は併用不可であることは記述した方がよさそうに感じます。

2025-01-20 10:34 UTC, chikamura commented on src/main/java/org/embulk/input/soql/ForceClient.java
> +            throw new ConfigException("No fields found in object: " + object);
nits: fields がないことのバリデーションを入れるのでしたら、後の fieldNames に対してバリデーションを入れた方がよさそうな気がします。また、null に加えて length が １以上の確認も追加した方が良いと思います。

2025-01-20 10:34 UTC, chikamura commented on src/main/java/org/embulk/input/soql/SoqlFilePlugin.java
> +            }
メモ

一度ファイルに書き出しているのはおそらく最後の commit 時に last_record を返すようにしたいためなので、
ファイルに書き出すのが必要なのはイテレーターの最後であとは以前のコードのように InputStream のままで取り扱えるはず
しかし、ファイル書き出しをしなくなることによる高速化の恩恵はそんなになさそうなので実装の手間を考えると一旦保留で良いかもしれない

2025-01-21 02:32 UTC, ziguzagu commented on src/main/java/org/embulk/input/soql/CsvFileInput.java
> +        List<CSVRecord> records = parser.getRecords();
https://developer.salesforce.com/docs/atlas.ja-jp.248.0.api_asynch.meta/api_asynch/asynch_api_bulk_query_intro.htm

1ファイルは最大1GBとなっているです。

2026-02-25 10:21 UTC, NamedPython approved these changes

2026-02-25 10:21 UTC, merged